### ISSUE TITLE
undefined method `paypal_form_tag' for #<ActionView::Base:0x23e946c>

### ISSUE THREAD

**Issue by kylebragger** [openhood/paypal#1]
using the block method (code pasted below) yields this error. running rails 2.3.2, latest rubygems

<% paypal_form_tag do %>
    <%= paypal_setup "#{@meal.name}", Money.us_dollar(@meal.price), 'shouldbepaypaladdress@kylebragger.com', :notify_url => 'fixme' -%>
    <button class="faux_button">Pay Now with PayPal</button>
<% end %>

**Comment by openhood** [comment]
Sorry I didn't see your message, I suppose it's much too late however the solution is simple and doesn't depend on Rails version. Inside helper you can find these comments:

  # For this to work you have to include these methods as helpers in your rails application.
  # One way is to add "include Paypal::Helpers" in your application_helper.rb
  # See Paypal::Notification for information on how to catch payment events. 

Just try that, it should work.
