### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by barmstrong** [openhood/paypal#2]
Hey there, awesome plugin!

Just wanted to mention two small things (very minor, but cost me a few hours trying to debug).
- In the readme where you say "When you're ready to go live...", you might also want to add instructions to add this:
  
  Paypal::Notification.ipn_url = "https://www.paypal.com/cgi-bin/webscr"

Also I wasn't sure where to add these so I put them in environment.rb.
- (This was the one that really threw me for a while).  In notification.rb you have this in the comments:
  
  #Example: 
  #Paypal::Notification.ipn_url = http://www.paypal.com/cgi-bin/webscr

I copied and pasted that in, but notice it doesn't have the 's' for 'https' !
Paypal displays a bizarre error message if you send it to http instead, and for the longest time I couldn't figure it out.

Thanks for the awesome plugin!
Brian

**Comment by openhood** [comment]
Yes it's true, version with http doesn't seem to work anymore, I've just send an update to fix that. Of course in the long run it would be much better if there would simply be a switch between sandbox and production and you wouldn't have to change neither Paypal::Notification.paypal_cert nor Paypal::Notification.ipn_url - I hope I will soon have time to do this change as well as others such as using rspec intead of test-unit.

**Comment by barmstrong** [comment]
thanks for the fix, much appreciated openhood :)
